spring:
  application:
    name: book-shop

  datasource:
    url: jdbc:postgresql://localhost:5432/bookshopdb
    username: Book
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
